# Generated by Django 4.1 on 2022-10-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
